name: Eternity-Hosting

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: checkout eternity-hosting
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization eternity-hosting
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.annklin }}
           git config --global user.email ${{ secrets.frnksulivan@gmail.com }}
           git config --global credential.helper store
           echo "https://${{ secrets.annklin }}:${{ secrets.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 }}@github.com" > ~/.git-credentials
       - name: cloning repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.annklin }}:${{ secrets.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 }}@${{ secrets.github.com/annklin/Eternity-host }} eternity
       - name: running eternity-hosting server
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd eternity
           docker build . -t eternity
           docker run eternity
       - name: loop eternity-hosting server
         continue-on-error: true
         run: |
              git clone https://github.com/${Ayanami} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "eternity-hosting : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.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 }}@github.com/${Ayanami} HEAD:eternity-hosting
